CREATE TABLE IF NOT EXISTS offers (
	TradingDate TEXT,
	TradingPeriod INTEGER,
	Site TEXT,
	ParticipantCode TEXT,
	PointOfConnection TEXT,
	Unit TEXT,
	ProductType TEXT,
	ProductClass TEXT,
	ReserveType TEXT,
	ProductDescription TEXT,
	UTCSubmissionDate TEXT,
	UTCSubmissionTime TEXT,
	SubmissionOrder INTEGER,
	Tranche INTEGER,
	MaximumRampUpMegawattsPerHour REAL,
	MaximumRampDownMegawattsPerHour REAL,
	PartiallyLoadedSpinningReservePercent REAL,
	MaximumOutputMegawatts REAL,
	ForecastOfGenerationPotentialMegawatts REAL,
	Megawatts REAL,
	DollarsPerMegawattHour REAL,
	FileLastModified TEXT,
	PRIMARY KEY (TradingDate, TradingPeriod, PointOfConnection, Unit, Tranche)
);
